# ==========================================
# CONEXÃO COM O BANCO DE DADOS (POSTGRESQL)
# ==========================================
spring.datasource.url=jdbc:postgresql://localhost:5432/financeapi
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================================
# CONFIGURAÇÕES DO HIBERNATE (ORM)
# ==========================================
# A mágica do "update": Cria tabelas se não existirem, mas NÃO apaga os dados ao reiniciar
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ==========================================
# LOGS DO CONSOLE (Para você ver o SQL rodando)
# ==========================================
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true